import { FRONTMATTER, SECTIONS, TRUST_INDICATORS, METADATA, SEVERITY_COLORS } from '../config/template-default.js';
import { FailureTypeLabel } from './failure-schema.js';
import { audit } from './tone-guide.js';

function formatDate(iso) {
  const d = new Date(iso);
  const pad = n => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function yamlFrontmatter(session) {
  const defaults = FRONTMATTER;
  const title = `AI Failure Retrospective: ${session.agent_name || 'unknown'} — ${FailureTypeLabel[session.failure_type] || 'Unknown'}`;
  const date = session.timestamp ? formatDate(session.timestamp) : '';

  const lines = ['---'];
  lines.push(`layout: ${defaults.layout || 'post'}`);
  lines.push(`title: "${title.replace(/"/g, '\\"')}"`);
  if (date) lines.push(`date: ${date} +0900`);
  if (defaults.categories) lines.push(`categories: [${defaults.categories.join(', ')}]`);
  lines.push(`tags: [ai, retrospective, ${session.failure_type || 'unknown'}]`);
  lines.push('---');
  return lines.join('\n');
}

function severityBadge(severity) {
  const map = { low: 'ℹ', medium: '⚠', high: '🔴', critical: '🚨' };
  return `${map[severity] || 'ℹ'} ${severity.toUpperCase()}`;
}

function buildTimeline(events) {
  if (!events || events.length === 0) return '';
  const lines = ['| Time | Event | Type |'];
  lines.push('|------|-------|------|');
  for (const ev of events.slice(0, 20)) {
    const time = ev.timestamp ? ev.timestamp.slice(11, 19) : '--:--:--';
    const desc = (ev.error_message || ev.user_input || ev.type || '').slice(0, 80);
    const type = ev.type || '';
    lines.push(`| ${time} | ${desc} | ${type} |`);
  }
  return lines.join('\n');
}

function trustFooter(stats, sessionHash, sessionId) {
  const lines = [
    '---',
    '',
    `*Generated by borgblog v0.1.0*`,
    `*Redacted: ${stats.total} fields (${stats.fields} fields, ${stats.keys} keys, ${stats.patterns} patterns)*`,
    `*Source: ${sessionId} (sha256: ${sessionHash.slice(0, 16)})*`,
    `*Generated: ${new Date().toISOString()}*`,
    `*Reviewer: _pending_*`,
  ];
  return lines.join('  \n');
}

export function render(session, events = []) {
  const frontmatter = yamlFrontmatter(session);
  const classificationLabel = session.llm_classification || FailureTypeLabel[session.failure_type] || 'Failure';
  const badge = severityBadge(session.severity || 'low');
  const tldr = session.llm_tldr || (session.error_message ? session.error_message.slice(0, 200) : 'No error details available.');

  let markdown = frontmatter;
  markdown += '\n\n';
  markdown += `## ${badge} — ${classificationLabel}\n\n`;
  markdown += `**Agent:** ${session.agent_name || 'unknown'}  \n`;
  markdown += `**Session:** ${session.session_id || 'unknown'}  \n`;
  markdown += `**Date:** ${session.timestamp ? formatDate(session.timestamp) : 'unknown'}  \n`;
  if (session.token_count) markdown += `**Tokens:** ${session.token_count.toLocaleString()}  \n`;
  if (session.duration) markdown += `**Duration:** ${session.duration}  \n`;
  markdown += '\n';

  markdown += `## TL;DR\n\n${tldr}\n\n`;

  markdown += `## Lessons Learned\n\n`;
  if (session.llm_lessons && session.llm_lessons.length > 0) {
    session.llm_lessons.forEach((lesson, i) => { markdown += `${i + 1}. ${lesson}\n`; });
  } else if (session.failure_type === 'tool_loop') {
    markdown += `1. The agent entered a retry loop — the same tool was called repeatedly without progress.\n`;
    markdown += `2. Root cause check: was the error transient or deterministic? Add circuit breaker.\n`;
  } else if (session.failure_type === 'timeout') {
    markdown += `1. Tool execution exceeded timeout threshold.\n`;
    markdown += `2. Consider splitting work into smaller chunks or increasing timeout.\n`;
  } else {
    markdown += `1. Review the root cause analysis below for the specific failure pattern.\n`;
    markdown += `2. Check if the failure was detected by the classifier: confidence ${(session.classifier_confidence || 0).toFixed(2)}\n`;
  }
  markdown += '\n';

  markdown += `## Skills Acquired\n\n`;
  const skillTags = session.skills || [];
  if (skillTags.length > 0) {
    markdown += skillTags.map(s => `\`${s}\``).join(' ') + '\n\n';
  } else {
    markdown += `_No skills codified from this session._\n\n`;
  }

  markdown += `## Root Cause\n\n`;
  markdown += `> ${session.llm_root_cause || session.error_message || 'No root cause identified.'}\n\n`;

  if (events.length > 0) {
    markdown += `## Execution Timeline\n\n`;
    markdown += buildTimeline(events) + '\n\n';
  }

  markdown += `## What Failed\n\n`;
  markdown += `${session.user_input || session.error_message || 'No details available.'}\n\n`;

  if (session.tool_result) {
    markdown += `## Evidence\n\n`;
    markdown += '```\n';
    markdown += typeof session.tool_result === 'string'
      ? session.tool_result.slice(0, 500)
      : JSON.stringify(session.tool_result, null, 2).slice(0, 500);
    markdown += '\n```\n\n';
  }

  const toneResult = audit(markdown);
  if (toneResult.violations.length > 0) {
    markdown += `## Tone Audit\n\n`;
    markdown += `Score: ${toneResult.score}/10  \n`;
    for (const v of toneResult.violations) {
      markdown += `- Banned word "${v.label}" found ${v.count} time(s)\n`;
    }
    markdown += '\n';
  }

  const sessionHash = session.session_hash || 'unknown';
  const stats = session.redaction_stats || { total: 0, fields: 0, keys: 0, patterns: 0 };
  markdown += trustFooter(stats, sessionHash, session.session_id || 'unknown');

  return markdown;
}
