import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { logSuccess, logInfo, logWarn, logPlain } from '../lib/logger.js';

const JEKYLL_CONFIG = `title: AI Retrospective Blog
description: >-
  AI agent failure retrospectives — automatically generated from session logs.
baseurl: ""
url: ""
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-feed
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - .gitignore
`;

const GEMFILE = `source "https://rubygems.org"
gem "jekyll", "~> 4.3"
gem "github-pages", group: :jekyll_plugins
`;

const INDEX_MD = `---
layout: default
title: AI Retrospective Blog
---

## Posts

{% for post in site.posts %}
- [{{ post.title }}]({{ post.url | relative_url }}) — {{ post.date | date: "%Y-%m-%d" }}
{% endfor %}
`;

const ABOUT_MD = `---
layout: default
title: About
permalink: /about/
---

AI agent failure retrospectives — automatically generated by [borgblog](https://github.com/oulico/borgblog) from session logs. Each post captures what went wrong, why, and what was learned.
`;

const NOT_FOUND_HTML = `---
layout: default
permalink: /404.html
---

# 404

Page not found. [Back to home]({{ site.baseurl }}/).
`;

export function run(options = {}) {
  const dirs = ['_posts'];
  for (const d of dirs) {
    if (!existsSync(d)) {
      mkdirSync(d, { recursive: true });
      logSuccess(`Created ${d}/`);
    }
  }

  const files = {
    '_config.yml': JEKYLL_CONFIG,
    'Gemfile': GEMFILE,
    'index.md': INDEX_MD,
    'about.md': ABOUT_MD,
    '404.html': NOT_FOUND_HTML,
  };

  for (const [name, content] of Object.entries(files)) {
    if (existsSync(name)) {
      logInfo(`Skipped ${name} (already exists)`);
      continue;
    }
    writeFileSync(name, content, 'utf-8');
    logSuccess(`Created ${name}`);
  }

  if (!existsSync('.gitignore')) {
    writeFileSync('.gitignore', '_site/\n.sass-cache/\n.jekyll-cache/\n.jekyll-metadata\nvendor/\n', 'utf-8');
    logSuccess('Created .gitignore');
  }

  logPlain('');
  logPlain('Next steps:');
  logPlain(`  1. bundle install`);
  logPlain(`  2. bundle exec jekyll serve`);
  logPlain(`  3. borgblog generate --log <session.jsonl>`);
  logPlain(`  4. borgblog publish`);
}
